### ISSUE TITLE
ValueError: Variable Wemb/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope

### ISSUE THREAD

**Issue by jasonustc** [tsenghungchen/SA-tensorflow#11]
I come into this error when running the code, any suggestions?

**Comment by jasonustc** [comment]
solved here: https://github.com/tensorflow/tensorflow/issues/6220

**Comment by chaiyixuan** [comment]
@jasonustc how to solve?

**Comment by LuDCD** [comment]
> 
> 
> @jasonustc how to solve?

I repalce `AdamOptimizer()` by `GradientDescentOptimizer()`.
