### ISSUE TITLE
Hi,Chen, where to get msvd_dataset_final.npz ?

### ISSUE THREAD

**Issue by ZJkerry** [tsenghungchen/SA-tensorflow#14]
thank you

**Comment by sl950313** [comment]
I'm also confused about the msvd_dataset_final.npz, hope the author to solve the issue. Best wishes.

**Comment by tsenghungchen** [comment]
The npz file consists of three keys: train, val, test. The values are the path to each video.

**Comment by Nadern96** [comment]
any solution ??
