### ISSUE TITLE
where is a data?

### ISSUE THREAD

**Issue by fodrh1201** [tsenghungchen/SA-tensorflow#3]
where can i get data?
there is a problem when I load video_data_path_train ...etc..

**Comment by tsenghungchen** [comment]
You need to change it to a data list that contains all the paths of your HDF5 data. You can see the "Data" section in the README file for more information. I'll upload an sample txt file later. Feel free to reply. Thanks!

**Comment by sxs4337** [comment]
Thanks for the great code.
Is there any script that can help generate the h5 files?
The sample getlist.py file reads from MSRVTT dataset, however, the example train_vn.txt file seems to be from the MSVD data. Could you please clarify for running a simple example.
Thanks.

**Comment by bitwangdan** [comment]
Thanks for answering my question
In you **input_generator.py**, **there is a feature_path**,what does it mean? In you README, you said it is a kind of input_path ,but how i can get it ? Can you tell me something?
