### ISSUE TITLE
Error in generate_nolabel

### ISSUE THREAD

**Issue by SeekPoint** [tsenghungchen/SA-tensorflow#7]
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
[h264 @ 0x163d0e0] missing picture in access unit
Traceback (most recent call last):
  File "hdf5_generator/generate_nolabel.py", line 88, in <module>
    get_label_list(fname)
  File "hdf5_generator/generate_nolabel.py", line 71, in get_label_list
    frame_len = get_total_frame_number(fname)
  File "hdf5_generator/generate_nolabel.py", line 33, in get_total_frame_number
    length = float(cap.get(cv2.cv.CV_CAP_PROP_FRAME_COUNT))
AttributeError: 'module' object has no attribute 'cv'
andy1028@andy1028-Envy:/media/andy1028/data1t/os_prj/github/SA-tensorflow$

**Comment by SeekPoint** [comment]
why cloesed?

**Comment by tsenghungchen** [comment]
You have to install the library and download the dataset yourself.
It's not an issue at all.
Thanks.

**Comment by VisheshTanwar-IITR** [comment]
Hey Chen
I am getting the same problem..
Can you please tell, which library we need to install and then which dataset we have to download?
thanks
