### ISSUE TITLE
About input_generator.py

### ISSUE THREAD

**Issue by bitwangdan** [tsenghungchen/SA-tensorflow#8]
In **input_generator.py** , there is a **feature_path** , what does it mean ? how can i get it?

**Comment by aoki1994** [comment]
Hi, do you know what the **feature_path** mean? I also have trouble with it. Does it means the weights from VGG-16 which is already trained?

**Comment by VisheshTanwar-IITR** [comment]
@bitwangdan 

Hello, Did you get the solution of above problem. I mean,  what is feature_path? and how to find them and give them to feature_path?

Please help
Thanks
